import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const T = {
  bg:          '#0d0d0d',
  surface:     '#111111',
  border:      '#2e2e2e',
  textPrimary: '#ededed',
  textSecond:  '#a1a1a1',
  textTert:    '#717171',
  accent:      '#ffffff',
};

const styles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 64,
    paddingHorizontal: 56,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.6,
    color: T.textPrimary,
    backgroundColor: T.bg,
  },
  disclaimer: {
    backgroundColor: '#0a0f1a',
    borderWidth: 1,
    borderColor: '#3b5998',
    borderRadius: 4,
    padding: 10,
    marginBottom: 20,
  },
  disclaimerText: {
    fontSize: 9,
    color: '#93c5fd',
    fontFamily: 'Helvetica-Bold',
  },
  header: {
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: T.accent,
    marginBottom: 4,
  },
  meta: {
    fontSize: 9,
    color: T.textTert,
  },
  slideCard: {
    marginBottom: 20,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 6,
    padding: 16,
    backgroundColor: T.surface,
  },
  slideHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 8,
    gap: 8,
  },
  slideNumber: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: T.textTert,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  slideTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: T.accent,
  },
  slideBody: {
    fontSize: 10,
    color: T.textSecond,
    lineHeight: 1.65,
  },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 56,
    right: 56,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: T.textTert,
    textAlign: 'center',
  },
});

export interface PitchDeckPdfProps {
  content: string;
  generatedAt: string;
}

interface ParsedSlide {
  number: string;
  title: string;
  body: string;
}

function parseSlides(content: string): ParsedSlide[] {
  const lines = content.split('\n');
  const slides: ParsedSlide[] = [];
  let current: ParsedSlide | null = null;

  for (const line of lines) {
    const match = line.match(/^##\s+Slide\s+(\d+):\s+(.+)$/);
    if (match) {
      if (current) slides.push(current);
      current = { number: match[1] ?? '', title: match[2]?.trim() ?? '', body: '' };
    } else if (current && line.trim()) {
      current.body += (current.body ? '\n' : '') + line.trim();
    }
  }
  if (current) slides.push(current);
  return slides;
}

export function createPitchDeckPdf({ content, generatedAt }: PitchDeckPdfProps) {
  const slides = parseSlides(content);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerText}>
            AI-GENERATED PITCH DECK SCRIPT — Review all financials and claims before presenting to investors. Not financial advice.
          </Text>
        </View>

        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Pitch Deck Script</Text>
          <Text style={styles.meta}>10 slides · Generated by Thunder · {generatedAt}</Text>
        </View>

        {/* Slides */}
        {slides.map((slide, i) => (
          <View key={i} style={styles.slideCard} wrap={false}>
            <View style={styles.slideHeader}>
              <Text style={styles.slideNumber}>Slide {slide.number}</Text>
            </View>
            <Text style={styles.slideTitle}>{slide.title}</Text>
            <Text style={{ ...styles.slideBody, marginTop: 8 }}>{slide.body}</Text>
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Thunder · thunderhk.ai · AI-generated pitch deck script · Not financial advice
          </Text>
        </View>
      </Page>
    </Document>
  );
}
