import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const T = {
  bg:          '#0d0d0d',
  surface:     '#111111',
  border:      '#2e2e2e',
  textPrimary: '#ededed',
  textSecond:  '#a1a1a1',
  textTert:    '#717171',
  accent:      '#ffffff',
  high:        '#ef4444',
  medium:      '#f59e0b',
  low:         '#6b7280',
};

const styles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 64,
    paddingHorizontal: 56,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.5,
    color: T.textPrimary,
    backgroundColor: T.bg,
  },
  disclaimer: {
    backgroundColor: '#0f0a0a',
    borderWidth: 1,
    borderColor: T.high,
    borderRadius: 4,
    padding: 10,
    marginBottom: 20,
  },
  disclaimerText: {
    fontSize: 9,
    color: '#fca5a5',
    fontFamily: 'Helvetica-Bold',
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: T.accent,
    marginBottom: 4,
  },
  meta: {
    fontSize: 9,
    color: T.textTert,
  },
  sectionLabel: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: T.textTert,
    marginTop: 18,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  itemRow: {
    marginBottom: 10,
  },
  itemTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: T.textPrimary,
    marginBottom: 2,
  },
  itemBody: {
    fontSize: 10,
    color: T.textSecond,
    lineHeight: 1.5,
  },
  priorityHigh:   { color: T.high },
  priorityMedium: { color: T.medium },
  priorityLow:    { color: T.low },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 56,
    right: 56,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: T.textTert,
    textAlign: 'center',
  },
});

export interface DataRoomPdfProps {
  content: string;
  stage: string;
  sector: string;
  generatedAt: string;
}

interface ParsedItem {
  priority: 'HIGH' | 'MEDIUM' | 'LOW' | null;
  title: string;
  body: string;
}

interface ParsedSection {
  heading: string;
  items: ParsedItem[];
}

function parseChecklist(content: string): ParsedSection[] {
  const lines = content.split('\n');
  const sections: ParsedSection[] = [];
  let currentSection: ParsedSection | null = null;
  let currentItem: ParsedItem | null = null;

  function flushItem() {
    if (currentItem && currentSection) {
      currentSection.items.push(currentItem);
      currentItem = null;
    }
  }

  for (const line of lines) {
    if (line.startsWith('## ')) {
      flushItem();
      if (currentSection) sections.push(currentSection);
      currentSection = { heading: line.slice(3).trim(), items: [] };
    } else if (line.startsWith('**') && line.endsWith('**')) {
      flushItem();
      const text = line.slice(2, -2).trim();
      const match = text.match(/^(HIGH|MEDIUM|LOW)\s+(.+)$/);
      if (match) {
        currentItem = { priority: match[1] as 'HIGH' | 'MEDIUM' | 'LOW', title: match[2] ?? text, body: '' };
      } else {
        currentItem = { priority: null, title: text, body: '' };
      }
    } else if (line.trim() && currentItem) {
      currentItem.body += (currentItem.body ? ' ' : '') + line.trim();
    }
  }

  flushItem();
  if (currentSection) sections.push(currentSection);
  return sections;
}

export function createDataRoomPdf({ content, stage, sector, generatedAt }: DataRoomPdfProps) {
  const sections = parseChecklist(content);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerText}>
            AI-GENERATED CHECKLIST — Items and priorities are indicative. Adapt to your specific investor's requirements and jurisdiction.
          </Text>
        </View>

        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Data Room Checklist</Text>
          <Text style={styles.meta}>
            Stage: {stage} · Sector: {sector} · Generated by Thunder · {generatedAt}
          </Text>
        </View>

        {/* Sections */}
        {sections.map((section, si) => (
          <View key={si}>
            <Text style={styles.sectionLabel}>{section.heading}</Text>
            {section.items.map((item, ii) => (
              <View key={ii} style={styles.itemRow}>
                <Text style={styles.itemTitle}>
                  {item.priority && (
                    <Text style={item.priority === 'HIGH' ? styles.priorityHigh : item.priority === 'MEDIUM' ? styles.priorityMedium : styles.priorityLow}>
                      {item.priority}{' '}
                    </Text>
                  )}
                  {item.title}
                </Text>
                {item.body ? <Text style={styles.itemBody}>{item.body}</Text> : null}
              </View>
            ))}
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Thunder · thunderhk.ai · AI-generated checklist · Not legal or financial advice
          </Text>
        </View>
      </Page>
    </Document>
  );
}
