import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const T = {
  bg:          '#0d0d0d',
  surface:     '#111111',
  border:      '#2e2e2e',
  textPrimary: '#ededed',
  textSecond:  '#a1a1a1',
  textTert:    '#717171',
  accent:      '#ffffff',
  disclaimerBg:     '#0a0f1a',
  disclaimerBorder: '#3b5998',
  disclaimerText:   '#93c5fd',
};

const styles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 64,
    paddingHorizontal: 56,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.55,
    color: T.textPrimary,
    backgroundColor: T.bg,
  },
  disclaimer: {
    backgroundColor: T.disclaimerBg,
    borderWidth: 1,
    borderColor: T.disclaimerBorder,
    borderRadius: 4,
    padding: 10,
    marginBottom: 20,
  },
  disclaimerText: {
    fontSize: 9,
    color: T.disclaimerText,
    fontFamily: 'Helvetica-Bold',
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: T.accent,
    marginBottom: 4,
  },
  meta: {
    fontSize: 9,
    color: T.textTert,
  },
  sectionLabel: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: T.textTert,
    marginTop: 16,
    marginBottom: 6,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  bodyText: {
    fontSize: 11,
    color: T.textSecond,
    lineHeight: 1.6,
  },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 56,
    right: 56,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: T.textTert,
    textAlign: 'center',
  },
});

export interface OnePagerPdfProps {
  content: string;
  generatedAt: string;
}

/** Parse the AI markdown output into sections for PDF rendering */
function parseSections(content: string): { heading: string; body: string }[] {
  const lines = content.split('\n');
  const sections: { heading: string; body: string }[] = [];
  let currentHeading = '';
  let currentBody: string[] = [];

  for (const line of lines) {
    if (line.startsWith('# ')) {
      if (currentHeading) sections.push({ heading: currentHeading, body: currentBody.join('\n').trim() });
      currentHeading = line.slice(2).trim();
      currentBody = [];
    } else if (line.startsWith('## ')) {
      if (currentHeading) sections.push({ heading: currentHeading, body: currentBody.join('\n').trim() });
      currentHeading = line.slice(3).trim();
      currentBody = [];
    } else {
      currentBody.push(line);
    }
  }
  if (currentHeading) sections.push({ heading: currentHeading, body: currentBody.join('\n').trim() });
  return sections;
}

function stripMarkdown(text: string): string {
  return text.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/^\[FOUNDER TO CONFIRM: /g, '[CONFIRM: ');
}

export function createOnePagerPdf({ content, generatedAt }: OnePagerPdfProps) {
  const sections = parseSections(content);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerText}>
            AI-GENERATED DOCUMENT — Verify all claims, metrics, and financial figures before sharing with investors.
          </Text>
        </View>

        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Investor One-Pager</Text>
          <Text style={styles.meta}>Generated by Thunder · {generatedAt}</Text>
        </View>

        {/* Sections */}
        {sections.map((section, i) => (
          <View key={i}>
            <Text style={styles.sectionLabel}>{stripMarkdown(section.heading)}</Text>
            {section.body.split('\n').filter((l) => l.trim()).map((line, j) => (
              <Text key={j} style={styles.bodyText}>
                {line.startsWith('- ') || line.startsWith('* ')
                  ? `• ${stripMarkdown(line.slice(2))}`
                  : stripMarkdown(line)}
              </Text>
            ))}
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Thunder · thunderhk.ai · AI-generated investor document · Not financial advice
          </Text>
        </View>
      </Page>
    </Document>
  );
}
